title: Andrea Margiovanni
description: SMC & DPO, Digital Consultant, AR Specialist, Business Analyst, Web & Security

url: https://margiovanni.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: stramargio
  twitter: stramargio
  mastodon: andrea
  email: andrea@margiovanni.com
  linkedin: margio

disqus:
    shortname: 
